server:
  port: 8081
spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://127.0.01:3306/videoblog-video?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver

